Repository tlammi/kratos, pull requests merged in 2019-12, with the labels that each got.

#30 Feature/doc fixes
  doc/protocol_spec.md
  script/run_pytest.py
Labels: documentation

#32 Feature/common entry point
  kratos/__main__.py
  kratos/unit/EMPTY
  kratos/unit/debugsub.py
Labels: enhancement

#34 Feature/gui
  LICENSE
  kratos/gui/__init__.py
  kratos/gui/platform_view.qml
  kratos/gui/platformscreen.py
  kratos/gui/screen.py
  requirements.txt
Labels: enhancement

#35 Feature/mqtt engine heartbeat
  kratos/mqttengine/__init__.py
  kratos/mqttengine/mqttengine.py
  kratos/mqttengine/mqttengineconfig.py
  kratos/unit/debugsub.py
Labels: enhancement

#37 Feature/database spec
  doc/datamodel.md
Labels: documentation

#45 Simple scripts to automatically run postgreSQL
  script/run_postgresql.sh
  script/run_psql.sh
Labels: enhancement

#42 Feature/buttons
  kratos/__main__.py
  kratos/button/__init__.py
  kratos/button/button.py
  kratos/button/tkbutton.py
  kratos/mqttengine/mqttengine.py
  kratos/unit/debugsub.py
  kratos/unit/judge.py
  script/pylintrc
Labels: bug, enhancement
